### ISSUE TITLE
make test randomly fails link_up(linkAC) test

### ISSUE THREAD

**Issue by jbdatko** [telehash/telehash-c#61] opened 2015-07-15 19:29 UTC
running `make test`, it randomly fails with: 

```
----------------------------------------------
ext_peer.c:69: test FAILED:
Failed test: link_up(linkAC)
----------------------------------------------
FAILED: ext_peer
```
re-running `make test` seems to pass, sometimes.

**Comment by quartzjer** [comment] 2015-07-18 18:04
Duplicate of #58 (I think)

**Closed by quartzjer** 2015-07-18 18:04 UTC
